version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE_TEST
      - image: jenkinsrise/cci-v2-docker-e2e:0.0.1
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "build":
      docker: *DOCKERIMAGE_TEST
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-v2{{ checksum "package.json" }}
        - run:
            name: Build
            command: |
              if [ "${CIRCLE_BRANCH}" == "build/stable" ]; then
                npm run build-prod
              else
                npm run build-stage
              fi
        - save_cache:
            key: node-cache-v2{{ checksum "package.json" }}
            paths:
              - ./node_modules
        - persist_to_workspace:
            root: .
            paths:
              - dist

  "stage":
      docker: &DOCKERIMAGE
        - image: jenkinsrise/cci-v2-launcher-electron:0.0.5
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-v2{{ checksum "package.json" }}
        - run:
            name: Stage
            command: node_modules/common-component/stage.sh
            environment:
              COMPONENTNAME: rise-twitter
        - persist_to_workspace:
            root: .
            paths:
              - version

  "deploy-beta":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-v2{{ checksum "package.json" }}
        - run:
            name: Deploy to beta
            command: node_modules/common-component/deploy.sh
            environment:
              COMPONENTNAME: rise-twitter

  "deploy-stable":
      docker: *DOCKERIMAGE
      steps:
        - checkout
        - attach_workspace:
            at: .
        - restore_cache:
            key: node-cache-v2{{ checksum "package.json" }}
        - run:
            name: Deploy to beta
            command: node_modules/common-component/deploy.sh
            environment:
              COMPONENTNAME: rise-twitter
              BRANCH: STABLE

workflows:
  version: 2
  workflow1:
    jobs:
      - "test"
      - "build":
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/
      - "stage":
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - build/stable
                - /^stage\/.*/
                - /^staging\/.*/
      - "deploy-stable":
          requires:
            - stage
          filters:
            branches:
              only:
                - build/stable

      - "deploy-beta":
          requires:
            - stage
          filters:
            branches:
              only:
                - master
